package rules

import "github.com/sothatsit/agent-permissions/internal/model"

var straceParser, breakdownStrace = wrapperBreakdown(
	wrapperDef{
		flags: []model.FlagDef{
			{Name: "--summary-syscall-overhead", Arg: true},
			{Name: "--stack-trace-frame-limit", Arg: true},
			{Name: "--relative-timestamps"},
			{Name: "--absolute-timestamps"},
			{Name: "--summary-wall-clock"},
			{Name: "--output-separately"},
			{Name: "--const-print-style", Arg: true},
			{Name: "--summary-sort-by", Arg: true},
			{Name: "--summary-columns", Arg: true},
			{Name: "--successful-only"},
			{Name: "--always-show-pid"},
			{Name: "--strings-in-hex"},
			{Name: "--interruptible", Arg: true},
			{Name: "--syscall-times"},
			{Name: "--syscall-limit", Arg: true},
			{Name: "--summary-only"},
			{Name: "--string-limit", Arg: true},
			{Name: "--kill-on-exit"},
			{Name: "--follow-forks"},
			{Name: "--stack-trace"},
			{Name: "--seccomp-bpf"},
			{Name: "--failed-only"},
			{Name: "--decode-pids", Arg: true},
			{Name: "--trace-path", Arg: true},
			{Name: "--decode-fds"},
			{Name: "--trace-fds", Arg: true},
			{Name: "--secontext"},
			{Name: "--detach-on", Arg: true},
			{Name: "--daemonize"},
			{Name: "--verbose", Arg: true},
			{Name: "--version"},
			{Name: "--summary"},
			{Name: "--columns", Arg: true},
			{Name: "--status", Arg: true},
			{Name: "--signal", Arg: true},
			{Name: "--output", Arg: true},
			{Name: "--inject", Arg: true},
			{Name: "--attach", Arg: true},
			{Name: "--abbrev", Arg: true},
			{Name: "--write", Arg: true},
			{Name: "--trace", Arg: true},
			{Name: "--quiet"},
			{Name: "--fault", Arg: true},
			{Name: "--debug"},
			{Name: "--argv0", Arg: true},
			{Name: "--user", Arg: true},
			{Name: "--tips"},
			{Name: "--read", Arg: true},
			{Name: "--help"},
			{Name: "--raw", Arg: true},
			{Name: "--kvm", Arg: true},
			{Name: "--env", Arg: true},
			// Multi-char short flags (must come before
			// their single-char counterparts for greedy
			// cluster matching).
			{Name: "-DDD"},
			{Name: "-ttt"},
			{Name: "-DD"},
			{Name: "-ff"},
			{Name: "-qq"},
			{Name: "-tt"},
			{Name: "-xx"},
			{Name: "-yy"},
			// Short flags with args.
			{Name: "-e", Arg: true, Prefix: true},
			{Name: "-o", Arg: true, Prefix: true},
			{Name: "-p", Arg: true, Prefix: true},
			{Name: "-u", Arg: true, Prefix: true},
			{Name: "-s", Arg: true, Prefix: true},
			{Name: "-a", Arg: true, Prefix: true},
			{Name: "-b", Arg: true, Prefix: true},
			{Name: "-I", Arg: true, Prefix: true},
			{Name: "-P", Arg: true, Prefix: true},
			{Name: "-X", Arg: true, Prefix: true},
			{Name: "-O", Arg: true, Prefix: true},
			{Name: "-S", Arg: true, Prefix: true},
			{Name: "-U", Arg: true, Prefix: true},
			{Name: "-E", Arg: true},
			// Short bool flags.
			{Name: "-A"}, {Name: "-c"}, {Name: "-C"},
			{Name: "-d"}, {Name: "-f"}, {Name: "-h"},
			{Name: "-i"}, {Name: "-k"}, {Name: "-n"},
			{Name: "-q"}, {Name: "-r"}, {Name: "-t"},
			{Name: "-T"}, {Name: "-v"}, {Name: "-V"},
			{Name: "-w"}, {Name: "-x"}, {Name: "-y"},
			{Name: "-z"}, {Name: "-Z"}, {Name: "-D"},
			{Name: "-Y"},
		},
		denyFlags: map[string]string{
			"-E": "-E/--env denied — can inject " +
				"dangerous environment variables. " +
				"Set env vars inline instead",
			"--env": "-E/--env denied — can inject " +
				"dangerous environment variables. " +
				"Set env vars inline instead",
		},
		denyRule: straceEnvInject,
	})
